# netlify.toml — routing for both DOP viewer and chat
[build]
  publish = "."

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["personas/**", "assets/**"]

# DOP viewer route (existing)
[[redirects]]
  from = "/dop/:id"
  to   = "/dop.html?id=:id"
  status = 200

# NEW: DOP chat route
[[redirects]]
  from = "/chat/:id"
  to   = "/chat.html?id=:id"
  status = 200

  [[scheduled]]
path = "/.netlify/functions/heygen_video_processor"
schedule = "*/2 * * * *"

# --- DOP context endpoint (no-cors, GET) ---
[[redirects]]
  from = "/dop-context"
  to = "/.netlify/functions/dop_context"
  status = 200

# --- Payment success redirect ---
[[redirects]]
  from = "/pay-success"
  to = "/pay-success.html"
  status = 200
