# netlify.toml — viewer-first routing
[build]
  publish = "."

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["personas/**", "assets/**"]

[[redirects]]
  from = "/dop/:id"
  to   = "/dop.html?id=:id"
  status = 200
