# netlify.toml — viewer-first routing (FINAL)

[build]
  publish = "."

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["personas/**", "assets/**"]

# /dop/:id -> HTML viewer page. The page fetches data via functions.
[[redirects]]
  from = "/dop/:id"
  to   = "/dop.html?id=:id"
  status = 200
