# netlify.toml — Functions + static site, esbuild bundling
[build]
  publish = "."
  # We keep all source in repo root; no framework build step.

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["personas/**", "assets/**"]
