# netlify.toml — Phase 1: Demo Delivery

[build]
  publish = "."
  functions = "functions"   # ← keep your current functions folder

[functions]
  node_bundler = "esbuild"

# --- Performance: cache static assets (overrides the catch-all below) ---
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# --- Performance: cache MP4 clips aggressively ---
[[headers]]
  for = "/**/*.mp4"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# --- Default: HTML + everything else stays fresh ---
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
